//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuspiciousObjectExporter.LocalResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SuspiciousObjectExporterConsole {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuspiciousObjectExporterConsole() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuspiciousObjectExporter.LocalResource.SuspiciousObjectExporterConsole", typeof(SuspiciousObjectExporterConsole).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Use Suspicious Object Exporter !!.
        /// </summary>
        internal static string ApplicationWelocomeString {
            get {
                return ResourceManager.GetString("ApplicationWelocomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==&gt;.
        /// </summary>
        internal static string ArrowIcon01 {
            get {
                return ResourceManager.GetString("ArrowIcon01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;==.
        /// </summary>
        internal static string ArrowIcon02 {
            get {
                return ResourceManager.GetString("ArrowIcon02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string ColonIcon {
            get {
                return ResourceManager.GetString("ColonIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string DirectorIcon01 {
            get {
                return ResourceManager.GetString("DirectorIcon01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        internal static string DivideIcon01 {
            get {
                return ResourceManager.GetString("DivideIcon01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string DivideIcon02 {
            get {
                return ResourceManager.GetString("DivideIcon02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [FAILED] Exception Message : .
        /// </summary>
        internal static string ExceptionTitleString {
            get {
                return ResourceManager.GetString("ExceptionTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please key in &quot;Enter&quot; to exit.
        /// </summary>
        internal static string ExitApplicationString {
            get {
                return ResourceManager.GetString("ExitApplicationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE :
        ///    SuspiciousObjectExporter.exe [/s [Start ID]] [/e [End ID]] [/f [y|n]] [/d]
        ///where
        ///    Start ID    The first ID for querying the suspicious object list
        ///    End ID      The latest ID for querying the suspicious object list
        ///
        ///    Options :
        ///        /s      Specifies the first ID of the suspicious object to be queried
        ///        /e      Specifies the latest ID of the suspicious object to be queried
        ///        /f      Enables the action which the console freeze after executed or not for PowerShell or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpInfoString {
            get {
                return ResourceManager.GetString("HelpInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [IGNORE].
        /// </summary>
        internal static string IgnoreString {
            get {
                return ResourceManager.GetString("IgnoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count of arguments is odd. It is illeage input..
        /// </summary>
        internal static string illeaglInfoString01 {
            get {
                return ResourceManager.GetString("illeaglInfoString01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count of arguments is bigger than 6.  It is illeage input..
        /// </summary>
        internal static string illeaglInfoString02 {
            get {
                return ResourceManager.GetString("illeaglInfoString02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some illeage arguments..
        /// </summary>
        internal static string illeaglInfoString03 {
            get {
                return ResourceManager.GetString("illeaglInfoString03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is illeage argument.
        /// </summary>
        internal static string illeaglInfoString04 {
            get {
                return ResourceManager.GetString("illeaglInfoString04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ID and End ID are required.
        /// </summary>
        internal static string illeaglInfoString05 {
            get {
                return ResourceManager.GetString("illeaglInfoString05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ID is must smaller than End ID.
        /// </summary>
        internal static string illeaglInfoString06 {
            get {
                return ResourceManager.GetString("illeaglInfoString06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting is finished !!.
        /// </summary>
        internal static string ImportFinishString {
            get {
                return ResourceManager.GetString("ImportFinishString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start to Export .
        /// </summary>
        internal static string ImportStartString {
            get {
                return ResourceManager.GetString("ImportStartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Suspicious Object List Successfully.
        /// </summary>
        internal static string ImportSuccessfully {
            get {
                return ResourceManager.GetString("ImportSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Input [start ID] for querying the suspicious object list : default = 0.
        /// </summary>
        internal static string InputInfoString01 {
            get {
                return ResourceManager.GetString("InputInfoString01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Input [end ID] for querying the suspicious object list : default = 0.
        /// </summary>
        internal static string InputInfoString02 {
            get {
                return ResourceManager.GetString("InputInfoString02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be numeric !!.
        /// </summary>
        internal static string NumericWarningString {
            get {
                return ResourceManager.GetString("NumericWarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of Suspicious Object is between.
        /// </summary>
        internal static string SORangeInfoString01 {
            get {
                return ResourceManager.GetString("SORangeInfoString01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string SORangeInfoString02 {
            get {
                return ResourceManager.GetString("SORangeInfoString02", resourceCulture);
            }
        }
    }
}
